name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug Environment Variables
        run: |
          echo "RAILWAY_TOKEN: ${RAILWAY_TOKEN:0:4}****"
          echo "DB_HOST: ${DB_HOST}"
          echo "DB_PORT: ${DB_PORT}"
          echo "DB_USERNAME: ${DB_USERNAME}"
          echo "DB_PASSWORD: ${DB_PASSWORD:0:4}****"
          echo "DB_NAME: ${DB_NAME}"
          echo "JWT_SECRET: ${JWT_SECRET:0:4}****"
          echo "ADMIN_PASSWORD: ${ADMIN_PASSWORD:0:4}****"
          echo "ADMIN_EMAIL: ${ADMIN_EMAIL}"
          echo "FRONT_END_URL: ${FRONT_END_URL}"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          FRONT_END_URL: ${{ secrets.FRONT_END_URL }}

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
